name: Execute test cases
on:
  push:
   branches:
     - main

jobs:
  excute-test-cases:
    name: excute-test-cases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: execute test case
        run: |
          echo "executing test code goes here..."
