name: Execute test cases
on:
  pull_request:
    types: [opened, reopened]

jobs:
  excute-test-cases:
    name: excute-test-cases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/github-script@v7
        id: set-result
        
        with:
            result-encoding: string
            script: |
            github.rest.issues.get({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
                   })
