name: Execute test cases
on:
  pull_request:
    types: [opened, reopened]

jobs:
  excute-test-cases:
    name: excute-test-cases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: issue comment
        uses: actions/github-script@v7
        with:
          script: |
              github.rest.issues.createComment({
              issue_number: ${{ github.event.issue.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "invalid environment. Please check if application and cluster names are typed correctly."
              })
              