name: Execute test cases
on:
  pull_request:
    types: [opened, reopened]

jobs:
  excute-test-cases:
    name: excute-test-cases
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/github-script@v7
        id: set-result
        with:
            script: |
              // Octokit.js
              // https://github.com/octokit/core.js#readme
              const octokit = new Octokit({
                auth: '${{ secrets.GITHUB_TOKEN }}'
              })

              await octokit.request('GET /repos/{owner}/{repo}/issues/comments', {
                owner: 'OWNER',
                repo: 'REPO',
                headers: {
                  'X-GitHub-Api-Version': '2022-11-28'
                }
              })
            result-encoding: string
  