name: execute test case

'on':
  pull_request:
    branches: 
      - main
    types: [ closed ]

jobs:
  execute-test-case:
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
        deployments: write
        contents: write
        checks: write
      steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: search execution comment
        id: search-execution-comment
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            comments = github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })
             console.log(comments)
