name: execute test case

'on':
  pull_request:
    branches: 
      - main
    types: [ closed ]

jobs:
  execute-test-case:
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
        deployments: write
        contents: write
        checks: write
      steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: search execution comment
        id: search-execution-comment
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
           async function getComments() {
            try {
                const response = await github.rest.issues.listComments({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo
                });
                
                const comments = response.data; // Assuming the response contains data array with comments
                const filteredComments = comments.filter(comment => comment.body.startsWith("execute_test_case"));
                return filteredComments;
            } catch (error) {
                console.error("Error fetching comments:", error);
                return []; // Return an empty array or handle the error as needed
            }
           }
            const comments = await getComments();
            if (comments.length === 1) {
            return comments[0].body
            } else {
             return 'false'
            }
      - name: Get result
        if: steps.search-execution-comment.outputs.result != 'false'
        run: |
             echo "execute test case code goes here"
             echo "${{steps.search-execution-comment.outputs.result}}"
