name: Sanity Test Workflow
on:
  pull_request:
    types: [opened, reopened, closed, labeled]
jobs:
  labeled:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'labeled'}}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: | 
             echo "labeled"
      # Add steps to run your sanity test here
  
  opened:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: | 
             echo "opened"
      # Add steps to run your sanity test here
  reopened:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'reopened' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: | 
             echo "reopened"
      # Add steps to run your sanity test here
  merged:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: | 
             echo "merged"
  closed:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed' && github.event.pull_request.merged != true }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: | 
             echo "closed"

