name: Sanity Test Workflow
on:
  pull_request:
    types: [labeled]
jobs:
  sanity_test:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'labeled'}}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: | 
             echo "${{ github.event.number }}"
      # Add steps to run your sanity test here

