name: branch-deploy

'on':
  issue_comment:
    types: [created]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      deployments: write
      contents: write
      checks: write
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, "execute_test_case")}}

    steps:
      - name: checkout to main
        uses: actions/checkout@v3
        with:
          ref: main
      - name: validate comment
        env:
        COMMENT_BODY: ${{github.event.comment.body}}
        id: validate-comment
        run: |
             if [[ "$COMMENT_BODY" == *"ibe"* ]]; then
             comment_validated=passed" >> "${GITHUB_OUTPUT}"
            else
             comment_validated=failed" >> "${GITHUB_OUTPUT}"
            fi

      - name: issue comment
        if: ${{ steps.validate-comment.outputs.comment_validated == 'failed' }}
        uses: actions/github-script@v6
        with:
          script: |
              github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.issue.number }},
              body: "invalid environment. Please check if application and cluster names are typed correctly."
              })
            

     