name: Issue Comment Workflow
on:
  issue_comment:
    types: [created]

jobs:
  process-comment:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Print the comment body
      run: |
      echo "Comment body: ${{ github.event.comment.body }}"
      
    # Add your steps here to process the comment
