name: Issue Comment Workflow
on:
  issue_comment:
    types: [created]

jobs:
  process-comment:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'execute_test_case')}}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      deployments: write
      contents: write
      checks: write
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Print the comment body
      run: |
           echo "Comment body: ${{ github.event.comment.body }}"
    - name: validate comment
      env:
        COMMENT_BODY: ${{github.event.comment.body}}
      id: validate-comment
      run: |
            if [[ "$COMMENT_BODY" == *"ibe"* ]]; then
            echo "comment_validated=passed" >> "${GITHUB_OUTPUT}"
            else
            echo "comment_validated=failed" >> "${GITHUB_OUTPUT}"
            fi

    - name: invalid environment
      if: ${{ steps.validate-comment.outputs.comment_validated == 'falied' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.issue.number }},
              body: "invalid ibe properties."
          })
